### ISSUE TITLE
`ylim()` causes errors in `geom_fit_text()`

### ISSUE THREAD

**Issue by alastairrushworth** [wilkox/ggfittext#11]
Hi @wilkox 

I've found that sometimes `geom_fit_text()` causes an error when `ylim()` is specified as part of the main plot call.  There's a simple example below.  It always fails if the `ylim()` is within the range of the `y` values for the `geom_bar()`. It also fails sometimes when the `ylim()` is near to (but not inside of the range of `y`.  Is that a bug, or is there a good reason why this shouldn't work?

Thanks!

Alastair

```
z = data.frame(x = letters[1:5], y = 0:4, lb = 3)

# this works
z %>%
  ggplot(aes(x = x, y = y, label = lb)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  ylim(-1, 6) + 
  geom_fit_text()

# this doesn't - ylim is inside the range of y
z %>%
  ggplot(aes(x = x, y = y, label = lb)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  ylim(0.5, 3) + 
  geom_fit_text()

# this doesn't - ylim is outside the range of y
z %>%
  ggplot(aes(x = x, y = y, label = lb)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  ylim(-0.1, 6) + 
  geom_fit_text()
```

**Comment by wilkox** [comment]
Thanks for reporting this Alastair! The error happens because when `geom_fit_text()` is called with only a `y` aesthetic (as opposed to either a `y` aesthetic plus a `height` argument, or `ymin`/`ymax` aesthetics), it automatically guesses upper and lower limits for the box based on the data. If these limits fall outside of the limits set by `ylim()` (as in your second and third examples), it results in the error you saw.

I think the best way to handle this would be to not draw any labels when the bounding box falls outside explicitly set plot limits, perhaps emitting a warning that they had been skipped. However, I'm curious about the use case explored in your examples – specifically, a continuous variable on the y axis but no explicit `ymin`/`ymax` or `height`, and y limits fixed with `ylim()`. It seems like plain old `geom_text()` would be better for this kind of situation:

``` r
library(tidyverse)
z = data.frame(x = letters[1:5], y = 0:4, lb = 3)
z %>%
  ggplot(aes(x = x, y = y, label = lb)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  ylim(-0.1, 6) + 
  geom_text()
```

![](https://i.imgur.com/RPt92f8.png)

<sup>Created on 2019-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If I changed `geom_fit_text()` to skip drawing the text labels as I described above, would that work for your use case?

**Comment by alastairrushworth** [comment]
Thanks for the quick response!  I think my use case is fairly simple here - so I might have misunderstood the `gg_fit_text()` parameters.  My not specifying `ymin/ymax` or `height` is really convenience - I like that I can just let `gg_fit_text()` guess from `x` and `y` what to do.  Is there a way these arguments could be added to the example with `ylim()` that avoids the error?

This isn't a huge deal for me and I don't necessarily think anything needs to be fixed - and as you say, maybe `geom_text()` is the way to go in the case, though I'd really like to keep the text scaling if possible.  Perhaps a more general argument for your suggestion to skip the labels with a warning is that I think if the main `ggplot()` part works then maybe we should not expect the annotation geom to cause an error.

Thanks again, it's much appreciated.

**Comment by wilkox** [comment]
You're definitely right that if `ggplot()` accepts the data and aesthetics then `geom_fit_text()` shouldn't stop with an error. I've just pushed a commit to the development version (df19c27) that fixes this and emits a warning instead.

I can't really think of an ideal behaviour that would work for your use case though. Any automatic method that tries to guess a more appropriate set of y limits for the box could still end up generating limits outside the plot limits, since `ylim()` by design can chew into the available plot area regardless of whether there is data there or not. I guess in defence of the 'skip-and-warn' behaviour is that this is also how ggplot2 treats `geom_bar()` if it falls outside the limits, so at least the plot is consistent:

``` r
library(tidyverse)
library(ggfittext)
z = data.frame(x = letters[1:5], y = 0:4, lb = 3)

# this works
z %>%
  ggplot(aes(x = x, y = y, label = lb)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  ylim(1, 8) + 
  geom_fit_text()
#> Warning: Removed 5 rows containing missing values (geom_bar).
#> Warning: Removed 2 rows where box limits were outside plot limits
#> (geom_fit_text)
```

![](https://i.imgur.com/Qwk3Ass.png)

<sup>Created on 2019-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by alastairrushworth** [comment]
That makes total sense.  I like the warn and skip approach - that does help with some of the things I was doing.    I need to think a bit harder about my own application but I don't think it's a `ggfittext` issue.  Thanks again for looking into this!
