### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by JegorG** [wilkox/ggfittext#21]
Thanks for creating this package! I was playing around a bit and I think I might have found some issues? Or maybe I dont understand the package properly . Some examples below

library(ggplot2)
library(ggfittext)
library(data.table)
library(patchwork)

set.seed(1)

df <- data.table(group1 = sample(letters[1:10], 100, replace = TRUE),
                 group2 = sample(letters, 100, replace = TRUE),
                 var1   = rnorm(100))

df_agg <- df[, .(var1 = abs(sum(var1))), by = c('group1', 'group2')][, label := round(var1 * 100, 2) %>% paste('%', sep = '')]

# Many labels are not shown

ggplot(df_agg, aes(x = group2, y = var1, fill = group1, label = label)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_bar_text(position = 'dodge', reflow = TRUE)

# Labels are shown, so its not shown above due to long name. A warning maybe?
# I would expect the labels to be on top of the bars

ggplot(df_agg, aes(x = group2, y = var1, fill = group1, label = str_sub(label, 1, 1))) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_bar_text(position = 'dodge', reflow = TRUE, place = 'top')

# No labels for group e, i,n 

ggplot(df_agg, aes(x = group2, y = var1, fill = group1, label = str_sub(label, 1, 1))) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_bar_text(position = 'dodge', reflow = TRUE, place = 'bottom')

# Probably not related, but all text disappears in the patchplot. Any idea why?

p1 <- ggplot(df_agg[group2 %in% c('s', 'w', 'i')], aes(x = group1, y = var1, fill = group2, label = label)) +
  geom_col(position = 'dodge') +
  geom_bar_text(position = 'dodge', reflow = FALSE)

p1 + p1 + p1 + p1 + plot_layout(ncol = 4)

# Using position_dodge2 does not work

ggplot(df_agg[group2 %in% c('s', 'w', 'i')], aes(x = group1, y = var1, fill = group2, label = label)) +
  geom_col(position = position_dodge(preserve = 'single')) +
  geom_bar_text(position = 'dodge', reflow = FALSE)

**Comment by wilkox** [comment]
Thanks for your interest in the package 😄

# Many labels not shown

This is because labels smaller than a certain point size (8 pt by default) are hidden. See the `min.size` argument:

``` r
library(tidyverse)
library(ggfittext)
library(data.table)
#> 
#> Attaching package: 'data.table'
#> The following objects are masked from 'package:dplyr':
#> 
#>     between, first, last
#> The following object is masked from 'package:purrr':
#> 
#>     transpose
library(patchwork)

set.seed(1)

df <- data.table(group1 = sample(letters[1:10], 100, replace = TRUE),
group2 = sample(letters, 100, replace = TRUE),
var1 = rnorm(100))

df_agg <- df[, .(var1 = abs(sum(var1))), by = c('group1', 'group2')][, label := round(var1 * 100, 2) %>% paste('%', sep = '')]


ggplot(df_agg, aes(x = group2, y = var1, fill = group1, label = label)) +
geom_bar(stat = 'identity', position = 'dodge') +
geom_bar_text(position = 'dodge', reflow = TRUE, min.size = 0)
```

![](https://i.imgur.com/JR2H1nK.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# I would expect the labels to be on top of the bars

`geom_bar_text()` will only place labels on bars if the space inside is too small to fit them without shrinking them smaller than `min.size`, AND the space on top of the bar can fit the text without it being smaller than `min.size`. This is usually the case with 'short' bars, where the limiting dimension is height, rather than 'narrow' bars, where the limiting dimension is width.

# No labels for group e, i,n

This is `min.size` again; even with `min.size = 0`, the text is so small as to be almost invisible:

``` r
library(tidyverse)
library(ggfittext)
library(data.table)
#> 
#> Attaching package: 'data.table'
#> The following objects are masked from 'package:dplyr':
#> 
#>     between, first, last
#> The following object is masked from 'package:purrr':
#> 
#>     transpose
library(patchwork)

set.seed(1)

df <- data.table(group1 = sample(letters[1:10], 100, replace = TRUE),
group2 = sample(letters, 100, replace = TRUE),
var1 = rnorm(100))

df_agg <- df[, .(var1 = abs(sum(var1))), by = c('group1', 'group2')][, label := round(var1 * 100, 2) %>% paste('%', sep = '')]

ggplot(df_agg, aes(x = group2, y = var1, fill = group1, label = str_sub(label, 1, 1))) +
geom_bar(stat = 'identity', position = 'dodge') +
geom_bar_text(position = 'dodge', reflow = TRUE, place = 'bottom', min.size = 0)
```

![](https://i.imgur.com/lzLdjFw.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# Probably not related, but all text disappears in the patchplot. Any idea why?

It's `min.size` again. You can play around with the text angle and padding to try and make it more visible:

``` r
library(tidyverse)
library(ggfittext)
library(data.table)
#> 
#> Attaching package: 'data.table'
#> The following objects are masked from 'package:dplyr':
#> 
#>     between, first, last
#> The following object is masked from 'package:purrr':
#> 
#>     transpose
library(patchwork)

set.seed(1)

df <- data.table(group1 = sample(letters[1:10], 100, replace = TRUE),
group2 = sample(letters, 100, replace = TRUE),
var1 = rnorm(100))

df_agg <- df[, .(var1 = abs(sum(var1))), by = c('group1', 'group2')][, label := round(var1 * 100, 2) %>% paste('%', sep = '')]

p1 <- ggplot(df_agg[group2 %in% c('s', 'w', 'i')], aes(x = group1, y = var1, fill = group2, label = label)) +
geom_col(position = 'dodge') +
geom_bar_text(position = 'dodge', reflow = FALSE, min.size = 0, angle = 90, padding.x = grid::unit(0.1, "mm"), fullheight = TRUE)

p1 + p1 + p1 + p1 + plot_layout(ncol = 4)
```

![](https://i.imgur.com/9nurJrR.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# Using position_dodge2 does not work

ggfittext doesn't support arguments to `position_dodge` yet.
