### ISSUE TITLE
Plotted colours different to specified color in geom_bar_text()

### ISSUE THREAD

**Issue by ds-jim** [wilkox/ggfittext#22]
I'm not certain but I think since updating ggplot to 3.3 the colour does not line up to that which is specified in the `col` argument.

Minimal example below.

```library(dplyr)
library(ggplot2)
library(ggfittext)

mtcars %>% 
  count(gear) %>% 
  ggplot(aes(x = gear, y = n)) +
  geom_bar(stat = "identity") +
  geom_bar_text(col = "red", 
                fontface = "bold")
```
![image](https://user-images.githubusercontent.com/32925514/83013340-c568ef00-a014-11ea-814c-b8fc5d910349.png)

Package versions;
ggfittext_0.8.1.9002 ggplot2_3.3.0.9000   dplyr_0.8.3 R version 3.5.1

**Comment by wilkox** [comment]
Thanks for reporting this! This behaviour was due to the way the the default value for `contrast` was being set in `geom_bar_text()`. I've updated the development version to use a more sophisticated default that behaves more like you would expect:

``` r
library(tidyverse)
library(ggfittext)

mtcars %>% 
  count(gear) %>% 
  ggplot(aes(x = gear, y = n)) +
  geom_bar(stat = "identity") +
  geom_bar_text(col = "red", fontface = "bold")
```

![](https://i.imgur.com/gsYJt4c.png)

<sup>Created on 2020-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
