### ISSUE TITLE
Using geom_bar_text() to plot two labels

### ISSUE THREAD

**Issue by viniciusoike** [wilkox/ggfittext#37]
Hello, I've been trying out `ggfittext` and find it to be fantastic!

I tried using `geom_bar_text()` to plot two labels inside the same bar plot. While it works it flags me with a strange warning. Is there a more appropriate manner to make such a plot?

> library(ggplot2)
> library(ggfittext)
> 
> df <- data.frame(
>   name = rownames(mtcars),
>   mtcars
> )
> 
> ggplot(df[1:5, ], aes(x = name, y = mpg)) +
>   geom_col() +
>   geom_bar_text(aes(label = name), place = "left") +
>   geom_bar_text(aes(label = round(mpg)), place = "right") +
>   coord_flip() +
>   theme_void()

> Warning messages:
> 1: In geom_bar_text(aes(label = name), place = "left") :
>   Ignoring unknown aesthetics: label
> 2: In geom_bar_text(aes(label = round(mpg)), place = "right") :
>   Ignoring unknown aesthetics: label

![image](https://user-images.githubusercontent.com/10688700/216126199-7541febb-8083-4e6f-96fd-f33a92c5d0ae.png)

**Comment by wilkox** [comment]
Hi @viniciusoike, thanks for your kind words about ggfittext! This bug is fixed in the development version of ggfittext (see #29). You can install the development version directly from GitHub if you want by running `devtools::install_github('wilkox/ggfittext')`. However, in your example please note that despite the warnings nothing is actually going wrong with the plot - so if you are happy to ignore the warnings you can just keep using the CRAN version.
